export const LANGUAGES = [
{ code: 'hi', name: 'Hindi' },
{ code: 'bn', name: 'Bengali' },
{ code: 'te', name: 'Telugu' },
{ code: 'ta', name: 'Tamil' },
{ code: 'mr', name: 'Marathi' },
{ code: 'gu', name: 'Gujarati' },
{ code: 'kn', name: 'Kannada' },
{ code: 'ml', name: 'Malayalam' },
{ code: 'pa', name: 'Punjabi' },
{ code: 'ur', name: 'Urdu' },
{ code: 'fr', name: 'French' },
{ code: 'es', name: 'Spanish' },
{ code: 'de', name: 'German' },
{ code: 'it', name: 'Italian' },
{ code: 'ja', name: 'Japanese' },
{ code: 'ko', name: 'Korean' },
{ code: 'zh-CN', name: 'Chinese (Simplified)' },
{ code: 'ar', name: 'Arabic' },
{ code: 'ru', name: 'Russian' },
{ code: 'pt', name: 'Portuguese' },
{ code: 'tr', name: 'Turkish' },
];